### ISSUE TITLE
Volume owners are different

### ISSUE THREAD

**Issue by chrunchyjesus** [linuxserver/docker-lidarr#29]
The owners of the volumes for lidarr are different.

## Expected Behavior
- `config`: owner is me (uid: 1000, gid: 1000)
- `music`: owner is me (uid: 1000, gid: 1000)
- `downloads`: owner is me (uid: 1000, gid: 1000)

Adding `downloads` or `music` as root folder inside lidarr should work.

## Current Behavior
- `config`: owner is me (uid: 1000, gid: 1000)
- `music`: owner is root (uid: 0, gid: 0)
- `downloads`: owner is root (uid: 0, gid: 0)

Adding `downloads` or `music` as root folder inside lidarr does not work.

## Steps to Reproduce

1. Use the yaml file below or the docker compose file from this repo.
2. The volumes should not exist at time of starting the container, so they will be automatically created.
3. After the container started, check who the owner of the volumes are with `ls -l`. It should match the current behavior described above.
4. Navigate to the web interface of lidarr.
5. Open the browser devtools (F12).
6. Under `Settings` -> `Media Management` -> `add root folder` you cannot select `downloads` or `music` as root folder.
7. In the network tab of the devtools, the returned error message from lidarr is `Folder is not writable by user abc`.
![image](https://user-images.githubusercontent.com/20382692/71478450-0c498300-27f0-11ea-8d46-b3d17fe80472.png)

## Environment
**OS:** [Raspbian Buster Lite](https://www.raspberrypi.org/downloads/raspbian/)
**CPU architecture:** `arm64`. It is a Pi4.
**How docker service was installed:** `sudo apt install docker`

## Command used to create docker container (run/create/compose/screenshot)
I used the ansible `docker_container` module to create and run the container, which is basically the same as a docker compose file with differnet syntax and some more options on top.
```yml
- name: start lidarr
  docker_container:
    name: lidarr
    image: linuxserver/lidarr:0.7.1.1381-ls44
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Vienna"
    volumes:
      - /mnt/data2/lidarr/config:/config
      - /mnt/data2/lidarr/music:/music
      - /mnt/data2/lidarr/downloads:/downloads
    published_ports:
      - "51050:8686"
    state: started
    restart_policy: unless-stopped
```
