### ISSUE TITLE
Not removing files

### ISSUE THREAD

**Issue by alpe12** [linuxserver/docker-lidarr#66]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
I select an album, click on delete, check "Delete the track files". It should remove the files from disk.

## Current Behavior
It removes the entry on Lidarr. But the files remain on disk.

If I try to remove a single file, it works:
```
|Info|MediaFileDeletionService|Deleting track file: /storage/music/Christina Perri/songs for rosie (2021)/01 - just be.mp3
|Debug|RecycleBinProvider|Attempting to send '/storage/music/Christina Perri/songs for rosie (2021)/01 - just be.mp3' to recycling bin
|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /storage/music/Christina Perri/songs for rosie (2021)/01 - just be.mp3
```

If I try to remove an album or artist the only thing in the log is this:
`|Debug|Api|[DELETE] /api/v1/album/2579?deleteFiles=true&addImportListExclusion=false&queryParams=%5Bobject%20Object%5D: 200.OK (131 ms)`
And no files are deleted.

I even tried setting permissions for the folder and files to 777. Same result, so it's not a permission issue.

## Environment
**OS:** Ubuntu
**CPU architecture:** arm64

## Command used to create docker container (run/create/compose/screenshot)
```
version: "2.1"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./config:/config
      - /media/alpe/b7a7b057-f89e-4f10-8f2e-dc7851d3c1f2/storage:/storage
    ports:
      - 127.0.0.1:8686:8686
    restart: unless-stopped
```

## Docker logs
[Lidarr.debug.txt](https://github.com/linuxserver/docker-lidarr/files/7748585/Lidarr.debug.txt)
